### PR TITLE
Adds query url + remove dup method

### PR DESCRIPTION
**Pull request by taylorjdawson**

### CODE REVIEW

**Comment by taylorjdawson** [comment]
@ray024 Basically when you search for something now the "Search" link, links to the tmbd site search results.

**Comment by jaye** [comment]
Thanks, @taylorjdawson. Could you do with the `shows` and `people` commands as well?

**Comment by taylorjdawson** [comment]
@ray024 how's that?

**Comment by jaye** [comment]
Great, thanks!

**Pull request merged**
